### ISSUE TITLE
Pb Install

### ISSUE THREAD

**Issue by FilaliM** [Deducteam/isabelle_dedukti#12]
After an install with opam, at the make step I have the following problem:

% make && make install
File "commands/dkcheck.ml", line 118, characters 2-7:
Error: Unbound module Cmd
File "commands/dkdep.ml", line 75, characters 2-5:
Error: Unbound module Cmd
File "commands/dkmeta.ml", line 117, characters 2-14:
Error: Unbound module Cmdliner.Cmd
File "commands/dkpretty.ml", line 28, characters 2-5:
Error: Unbound module Cmd
File "commands/dkprune.ml", line 279, characters 2-14:
Error: Unbound module Cmdliner.Cmd
File "commands/dktop.ml", line 15, characters 2-14:
Error: Unbound module Cmdliner.Cmd

I did not find any file with the suffix .Cmd ?

Thanks

**Comment by fblanqui** [comment]
Hi. It is not a problem related to isabelle_dedukti. If you have problems installing dedukti, please open an issue on https://github.com/Deducteam/dedukti instead. Before doing make && make install, you need to check that you have all the dependencies already installed.

**Comment by fblanqui** [comment]
Note that, in dedukti/master, the command is now "dk check" instead of "dkcheck".

**Comment by fblanqui** [comment]
CI works well for dedukti (see https://github.com/Deducteam/isabelle_dedukti/pull/13)
For lambdapi, the output of isabelle_dedukti must be fixed since implicit arguments are now enclosed between square brackets instead of curly brackets. I am going to fix it too.

**Comment by fblanqui** [comment]
CI for lambdapi fixed in https://github.com/Deducteam/isabelle_dedukti/pull/14.
