### ISSUE TITLE
Not all theory files are exported

### ISSUE THREAD

**Issue by sacerdot** [Deducteam/isabelle_dedukti#28]
I have the impression that only the recursive dependencies of Complex_Main can be exported.

Esample of missing theory:  HOL/Lattice/Orders.thy

**Comment by sacerdot** [comment]
Ok, I see. The content of the src/HOL library of Isabelle is not a single session, but multiple ones (see the ROOT file there).
The one named HOL is rooted in Complex_Main + Main and thus only their dependencies are exported.

However, one can convert to Dedukti other sessions, even if there are bugs (at least for sessions not in the standard library).

This issue can be closed I think, but bug reports will follow.

**Comment by fblanqui** [comment]
Hi Claudio. I close this issue. With the merge of #16 it is now possible to export other developments, including those of AFP.
