### ISSUE TITLE
ROOT Dedukti_Base seems wrong

### ISSUE THREAD

**Issue by yannl35133** [Deducteam/isabelle_dedukti#5]
Based on my understanding on how this file works, and the files in my Isabelle directory, it seems that Dedukti_Base should be 
```
session Dedukti_Base in "Ex/Base" = Pure +
  sessions
    "Pure-Examples"
  theories
    "Pure-Examples.First_Order_Logic"
    "Pure-Examples.Higher_Order_Logic"
```

Also, executing 
`isabelle dedukti_build && isabelle dedukti_import -o export_standard_proofs Dedukti_Base`
as proposed by the README no longer complains about not being able to load the theory, but instead that some proof `in thm "First_Order_Logic.conjE"` is absent.

**Comment by makarius** [comment]
See now ce9e154bcb7
